namespace ShopDrawing.Plugin.Modules.Accessories
{
    internal sealed record ShopdrawingWallAccessorySnapshot(
        string WallCode,
        string SpecKey,
        string Application,
        double WallLengthM,
        double WallHeightM,
        double NetAreaM2,
        int PanelCount,
        double JointLengthM,
        double VerticalJointLengthM,
        double TopEdgeLengthM,
        double TopCenterLengthM,
        double TopPerimeterLengthM,
        double TopFreeLengthM,
        double BottomEdgeLengthM,
        double EndCenterLengthM,
        double EndPerimeterLengthM,
        double EndFreeLengthM,
        double ExposedEndLengthM,
        double TotalExposedEdgeLengthM,
        double OpeningPerimeterM,
        double OpeningPerimeterTwoFacesM,
        int OpeningCount,
        double DoorOpeningPerimeterM,
        double NonDoorOpeningPerimeterM,
        int DoorOpeningCount,
        int NonDoorOpeningCount,
        double OpeningVerticalEdgesM,
        double OpeningTopLengthM,
        double OpeningSillLengthM,
        double TekScrewQty,
        double PanelSupportBracketQty);
}
